name: Build and deploy Node.js app to Azure Web App - messages-service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install OpenSSL 1.1 (for mongodb-memory-server)
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://launchpadlibrarian.net/673948708/libssl1.1_1.1.1f-1ubuntu2.22_amd64.deb
          sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.22_amd64.deb

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build --if-present

      - name: Run tests
        run: npm test -- --detectOpenHandles

      - name: Zip artifact
        run: zip -r release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6B1D7DDA88DC479E8F0BE308054DA69F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_469AA5BDE18540C1B0CBB14136CFE0A6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0E42B0639B9044C3B48BAB8E53D72E4C }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'messages-service'
          slot-name: 'Production'
          package: .
